### ISSUE TITLE
id as i64

### ISSUE THREAD

**Issue by nitesh-jaswal** [nitesh-jaswal/bubble-it#5]
https://github.com/nitesh-jaswal/bubble-it/blob/ff0532703214fe02ed92a09a2fa0fa6ec9481bb4/server/src/messages.rs#L15

@ms747 Will saving id as i64 be a problem? I was going to store a string UUID. Would using i64 be better in any way?

**Comment by ms747** [comment]
It's just for the time being. Feel free to use UUIDs. Make sure to update the `messages` table likewise.
